language: perl

perl:
- '5.20'
- '5.18'
- '5.16'
- '5.14'
- '5.12'
- '5.10'
- '5.8'

install:
- cpanm --quiet --notest
  Devel::Cover::Report::Coveralls
  YAML::Pegex

script:
- PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine
  prove -lv t/
- cover

after_success:
- cover -report coveralls

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
